apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rayzi/front2:1.0
        env:
          - name: BACKEND_URL
            value: "http://backend-service:5000"
        ports:
        - containerPort: 80
